name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Show Visual Studio installations
        shell: pwsh
        run: |
          & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -all -products * -format json

      - name: Build
        shell: pwsh
        run: ./build.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ./~build/deploy/*.zip
